# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFunctionApp@2
  inputs:
    connectedServiceNameARM: 'Goco-Azure-Connection'
    appType: 'functionApp'
    appName: 'goco-cert-automation'
    deployToSlotOrASE: true
    resourceGroupName: 'cert-automation-group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'